config/routes.rb
DepotOnja::Application.routes.draw do  
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  
  
  scope '(:locale)' do    
    resources :users
    resources :orders
    resources :line_items do
      collection do
        post "decrement" => "line_items", :as => :decrement
      end
    end
    resources :carts      
    resources :products do    
      get :who_bought, :on => :member
    end    
    root :to => 'store#index', :as => 'store'
  end 

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy 
  
  def add_product(produit_id)
    current_item = line_items.find_by_product_id(produit_id)
    if current_item
      current_item.quantity += 1 unless current_item.quantity.nil?    
    else
      current_item = line_items.build(:product_id => produit_id)
      current_item.quantity =1 #set quantity 1 when create line items
    end
    current_item  
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def total_items
    line_items.sum(:quantity)
  end 

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart  
  
  def total_price
    product.price * quantity unless quantity.nil?
  end  
  
  def decrement_item(line_item)
    line_item.quantity -=1 unless line_item.quantity<1
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  PAYMENT_TYPES = PayType.all
  
  validates :name, :address, :email, :pay_type, :presence => true
  #validates :pay_type, :inclusion => PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end          
  end
  
end

app/models/pay_type.rb
class PayType < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  
  validates :title, :description, :image_url, :presence => true
  validates :title, :uniqueness => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :image_url, :format => {
                                      :with => %r{\.(jpeg|jpg|gif|png)$}i,
                                      :message => 'Verify your image type'
                                    }
                                    
                                    
  has_many :line_items
  has_many :orders, :through => :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private 
  def ensure_not_referenced_by_any_line_item
    
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line items present')
      return false
    end
    
  end

end

app/models/user.rb
class User < ActiveRecord::Base   

  after_destroy :ensure_an_admin_remains  
  attr_accessor   :password
  before_save :encrypt_password
  
  validates :name, :presence => true, :uniqueness => true  
  validates :password, :confirmation => true      
  
  def encrypt_password
    if password.present?      
      self.salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end
  
  def self.authenticate(name, password)
    user = find_by_name(name)
    if user && user.hashed_password ==  BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
  
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end 
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.xml
  skip_before_filter :authorize, :only => [:create, :update, :destroy]

  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.xml
  def show
    
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Inexisting cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid Cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @cart }
      end
    end
    
  end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
    #@cart = Cart.find(params[:id])
    @cart = current_cart    
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to(store_url) }
      format.js
      format.xml  { head :ok }
    end
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition      
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/file_m_anage_helper.rb
module FileMAnageHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DepotOnja</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %>  
  <%= javascript_include_tag "jquery.min" %>
  <%= javascript_include_tag "jquery_ujs" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery-ui-1.8.12.custom.min" %>  
  <%= javascript_include_tag "jquery.highlightFade" %>
  <%= csrf_meta_tag %>
</head>
<body id="store">
  
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
    <% unless session[:user_id] %>
      <span class="login">
        <%= link_to 'Log on', login_path %><br />
      </span>    
    <% end %>
  </div>
  
  <div id="columns">
    <div id="side">
      <%= form_tag store_path, :class => 'locale' do %>
        <%= select_tag 'set_locale',options_for_select(LANGUAGES, I18n.locale.to_s),:onchange => 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$(function(){$('.locale input').hide();});" %>
      <% end %>


    <% if @cart %>
      <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
        <%= render @cart %>
      <% end %>
    <% end %>

      <%= link_to t('.home'), store_path, :locale => params[:locale] %><br />
      <a href="http://www..../faq" ><%= t('.questions') %></a><br />
      <a href="http://www..../news" ><%= t('.news') %></a><br />
      <a href="http://www..../contact" ><%= t('.contact') %></a><br />
      
      <% if session[:user_id] %>
        <br />
          <%= link_to 'Orders', orders_path %><br />
          <%= link_to 'Products', products_path %><br />
          <%= link_to 'Users', users_path %><br />          
          <br />
          <%= button_to 'Logout', logout_path, :method => :delete %>
      <% end %>

      </div>
  </div>
  
  <div id="main">
    <%= yield %>
  </div>

</body>
</html>

app/views/notifier/order_received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<table>
<tr>
  <th colspan="2" >Qty</th>
  <th>Description</th>
</tr>
  <%= render @order.line_items %>
</table>
We'll send you a separate e-mail when your order ships.

app/views/notifier/order_shipped.text.erb
<h3>Pragmatic Order Shipped</h3>
<p>
This is just to let you know that we've shipped your recent order:
</p>
<table>
<tr><th colspan="2" >Qty</th><th>Description</th></tr>
 <%= render @order.line_items %>
</table>